### DISCUSSION TITLE
[K8S] Stuck in a boot loop `Failure message: Authorization header missing.` from service running the file as root works.

### DISCUSSION THREAD

**Discussion by ModdingFriendly** [RandomNinjaAtk/arr-scripts#325] [Q&A] [answered]
I imagine this will boil down to there's some weird thing that I'm doing in K8S but some help would be amazing if there is something I've overlooked. I pass in the env vars of PUID and PGID of 1001/100 which becomes abc/abc (who owns config.xml) 

Looking at `/config` all script files are owned by root but that doesn't stop me from `su`'ing as `abc` and running them manually and having the script work. But when it is running as part of the service they appear to fail with a bunch of auth failures. 

If you can think of any obvious gatchas please let me know 🙏  

[sonarr-86747594f-k72ng_sonarr.log](https://github.com/user-attachments/files/17581463/sonarr-86747594f-k72ng_sonarr.log)

If sharing my K8S deployment would help I can fire it up, but I don't think it's particularly interesting

**Comment by ModdingFriendly** [comment, marked as answer]
It looks like wither just my setup in K8S has an issue or there is some Networking Hijinx going on alas, I fixed it by just overwriting the defaults within `/config/extended/function` 

```yaml
        - name: radarr-sidecar
          image: alpine
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              echo "Installing dependencies...";
              apk add --no-cache bash curl;
              echo "Starting arr-scripts init...";
              wget -O /custom-cont-init.d/script_init.bash https://raw.githubusercontent.com/RandomNinjaAtk/arr-scripts/main/radarr/scripts_init.bash;
              chmod +x /custom-cont-init.d/script_init.bash;
              cat /custom-cont-init.d/script_init.bash | /bin/bash;

              # Replace arrPort and arrUrl in functions.bash
              echo "Replacing default URL params with K8S services...";
              sed -i 's|arrPort=.*|arrPort="80"|' /config/extended/functions;
              sed -i 's|arrUrl=.*|arrUrl="http://radarr.media.svc.cluster.local"|' /config/extended/functions;
              sed -i 's|arrApiKey=.*|arrApiKey="$API_KEY"|' /config/extended/functions;

              echo "Starting arr-scripts services...";
              for script in /custom-services.d/*; do
                [ -x "$script" ] && /bin/bash "$script" &
              done
              wait
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: radarr-api-key
                  key: credential
          volumeMounts:
            - name: final-config-volume
              mountPath: /config
```
